### ISSUE TITLE
scrolling issue with the context menu

### ISSUE THREAD

**Issue by isaacplmann** [isaacplmann/ngx-contextmenu#6]
_From @shahbazshueb on January 10, 2017 10:1_

When the context-menu is open in a scrollable content then the menu also scrolls down instead of staying fixed at its position. The menu should close when the content is scrolled down or it should stay fixed at the position.
![context menu scroll problem](https://cloud.githubusercontent.com/assets/10958507/21801963/ab13876e-d745-11e6-929b-7066891bf4a5.PNG)

_Copied from original issue: isaacplmann/angular2-contextmenu#40_

**Comment by isaacplmann** [comment]
You're right.  Do you know how to get the parent element that is the scroll container for a particular element?  I have a scroll listener for the body, but not for an arbitrary scroll container.

**Comment by Yura13** [comment]
Adding listener for mousewheel(Chrome, IE, Opera, Safari) and DOMMouseScroll(Firefox) partly solve the problem.

**Comment by Yura13** [comment]
any updates?

**Comment by isaacplmann** [comment]
I haven't had time to work on this for a while.  I'd like to work on it soon though.

Can you file window resize and setting focus as separate issues?

PRs always welcome.

**Comment by Yura13** [comment]
ok)

**Comment by achyutgp** [comment]
@isaacplmann Any updates? Is this issue fixed?

**Comment by isaacplmann** [comment]
Yes, actually this is fixed.  I should close it.  Scrolling now closes the context menu.

**Comment by achyutgp** [comment]
Hey, I still see this issue open on the latest version.
Unable to close the context-menu on scroll.
Kindly can you help me in fixing this..

**Comment by isaacplmann** [comment]
Ah, you're right.  There's a listener for the window scroll, but not for an arbitrary element scrolling.  Not sure how to fix this.  PR and/or ideas welcome.

**Comment by johaven** [comment]
+1 same problem

**Comment by isaacplmann** [comment]
I'm working on a new version using the `@angular/cdk/overlay` that can solve this problem by you putting `cdkScrollable` directives on any element that you want to close the context menu when it scrolls.  The new version is being worked on in the `cdk` branch.

**Comment by isaacplmann** [comment]
Try using `cdkScrollable` along with version `2.0.0-beta.1`

**Comment by achyutgp** [comment]
@isaacplmann , should ngx-contextmenu be upgraded to 2.0.0-beta.1?

**Comment by isaacplmann** [comment]
Yes, ngx-contextmenu needs to be updated to `2.0.0-beta.x` to use `cdkScrollable`.  However `2.0.0-beta.1` wasn't built correctly.  Use the latest beta.

**Comment by achyutgp** [comment]
@isaacplmann , Using latest beta `2.0.0-beta.4`,  I see an issue with contextMenu.component.js. Error says `'Cannot read property filter of undefined'`. It points to `ContextMenuComponent.setVisibleMenuItems`.
I do not see this error in the lower versions.

**Comment by isaacplmann** [comment]
@achyutgp I see the line that causes the error, and I could blindly fix it, but I'm curious why this is happening.

The only reason `menuItems` would be `undefined` there is if the `AfterContentInit` hook hasn't finished when you try to trigger the context menu.  That specific part of the library hasn't changed from 1.x to 2.x.

Are you manually triggering the context menu in a constructor or `ngOnInit`?

**Comment by achyutgp** [comment]
@isaacplmann , Yep! I am triggering the context-menu in `ngOnInit`. But, the same worked in lower versions of the library `(v1.3.5)`.

**Comment by isaacplmann** [comment]
@achyutgp It's a race condition.  My changes in other parts of the code could have made it so that the `menuItems` are not found before your `ngOnInit` code fires, but there's no guarantee it will stay that way.  Try putting your code in `ngAfterContentInit` or wrapping it in a `setTimeout`.

My "fix" would stop the error but wouldn't show a context menu, since I don't have any of the `menuItems` yet.  Hm...  I could potentially solve this using a `Subject` to emit the `menuItems` and show the context menu whenever they're available.  I'm not sure how soon I'll get to adding that functionality though.  I'll create a separate issue to track this.

**Comment by achyutgp** [comment]
@isaacplmann Yeah I get your point. Now I have placed the context-menu code block in `ngAfterContentInit` and also tried wrapping it inside a `setTimeout,` but I see no luck.. I do not see the previous error, but the context-menu is NOT rendered.

**Comment by isaacplmann** [comment]
That seems like a css bug.  Can you inspect the DOM and look for `body > .cdk-overlay-container` at the end of the body?  `.cdk-overlay-container` should fill the whole viewport and `.cdk-overlay-pane` inside of it should be absolutely positioned wherever you clicked.

There's also [this comment](https://github.com/isaacplmann/ngx-contextmenu/issues/63#issuecomment-340437207) which might help you.

**Comment by johaven** [comment]
@isaacplmann I use 2.0.0-beta.5 with Angular 5, context stays fixed at its position when scrolling (no errors in console), same behavior as on 1.x and Angular 4 builds.

Current content:
```html
<div class="cdk-overlay-container"><div id="cdk-overlay-2" class="cdk-overlay-pane ngx-contextmenu" dir="undefined" style="pointer-events: auto; top: 342px; left: 365px;"><context-menu-content _nghost-c4=""><div _ngcontent-c4="" class="dropdown open ngx-contextmenu" tabindex="0">
<context-menu-content>
<div _ngcontent-c4="" class="dropdown open ngx-contextmenu" tabindex="0">
      <ul _ngcontent-c4="" class="dropdown-menu" style="float: none;" tabindex="0">
		.....
      </ul>
    </div>
  </context-menu-content>
</div>
```

**Comment by achyutgp** [comment]
@isaacplmann , @johaven , I use `2.0.0-beta-5` with `Angular 4`. I do not see the context-menu opening.
When I inspect the DOM, `.cdk-overlay-container` is empty.

Current content:

`<div class="cdk-overlay-container"></div>`

**Comment by johaven** [comment]
Did you try this: https://github.com/isaacplmann/ngx-contextmenu/issues/63#issuecomment-340437207 ?

**Comment by achyutgp** [comment]
@johaven , Yeah I get the context-menu **using breakpoints** only when I add the below styling. 
```css
.ngx-contextmenu ul {
  display: block;
}
```
Else, I could not open the menu even using breakpoints.

**Comment by johaven** [comment]
@achyutgp it's the same for every one with the beta version at this time ;)

**Comment by achyutgp** [comment]
@johaven , even you do not see the context-menu on adding the CSS?

**Comment by johaven** [comment]
@achyutgp without this CSS style the context-menu doesn't show up

**Comment by achyutgp** [comment]
@johaven , **I DO NOT see the context-menu even after using the CSS style**. Context-menu opens and closes automatically. I could see the opening of context-menu using breakpoints by adding this CSS style.

**Comment by johaven** [comment]
@achyutgp AH ! I use 2.0.0-beta-5 with Angular 5 (not 4 in your case), that's probably why we do not have the same behavior

**Comment by isaacplmann** [comment]
@achyutgp Do you have more than one `<context-menu>` component in your app?  I had an error like you describe in my app earlier this week.  It turned out to be a bug in my app code not the library.  Here's what was happening for me:

P1. I had a `<context-menu>` component on the screen that I wanted to open.
P2. I had a second `<context-menu>` component rendered on the screen, that I didn't realize was there and it had a dynamic list of `contextMenuItem`s that was empty.
1. I right click to open the first context menu.
2. The first context menu triggers.
3. Immediately afterward, the second (empty) context menu triggers.
4. It looks like there's no context menu on the screen.

The way I fixed it was to pass a reference to the first context menu in the `show` event so that the second context menu would not try to show itself.  It could be that the `1.3.5` behavior was to show both context menus at the same time and I didn't notice because the second context menu was always empty.

If this doesn't help you, please post a repo that reproduces your issue.  Or alternatively you could sign up for a [codementor](https://www.codementor.io/isaacplmann?utm_source=github&utm_medium=button&utm_term=isaacplmann&utm_campaign=github) session with me and I'll help debug your app.

**Comment by isaacplmann** [comment]
The bootstrap 4 style bug is fixed `2.0.0-beta.6`.  See issue #63.

@johaven in order for the scrolling of an element to trigger a close of the context menu, you need to put a `cdkScrollable` directive on the element that scrolls.  Like this:

```
<div cdkScrollable style="height: 200px; overflow: auto;">
  <ul>
    <li *ngFor="item of items">{{item}}</li>
  </ul>
</div>
<context-menu>
  ...
</context-menu>
```

**Comment by johaven** [comment]
@isaacplmann It's ok for css style with beta 6
But for the scroll, it does not seem to work. 
Have you tried with a table?
<img width="774" alt="capture d ecran 2017-11-06 a 16 32 52" src="https://user-images.githubusercontent.com/5459596/32449102-fe1298bc-c310-11e7-8b26-5f8fce798551.png">

About CDK and Angular 5:
```
npm WARN @angular/cdk@2.0.0-beta.12 requires a peer of @angular/core@~4.4.4 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/cdk@2.0.0-beta.12 requires a peer of @angular/common@~4.4.4 but none is installed. You must install peer dependencies yourself.
```

**Comment by isaacplmann** [comment]
@johaven 

The warning from the cdk is in their court, not mine.  It looks like they're planning to address this today.  See [this issue](https://github.com/angular/material2/issues/7780).

It looks like you're putting the `cdkScrollable` on the correct element, but there may be another element might be scrolling as well.  It's hard for me to debug remotely.

**Comment by johaven** [comment]
@achyutgp @isaacplmann i have a strange behaviour on Firefox (56.0.2), context-menu opens and closes instantly.
No problem with Chrome and Safari.

**Comment by isaacplmann** [comment]
@johaven thanks for reporting the firefox issue.  I see what you're talking about.  Please open a separate issue so that I can track it.

**Comment by achyutgp** [comment]
@johaven , @isaacplmann , I see the same issue on Chrome and everything works fine for me in Firefox.
I use this `Version 62.0.3202.89 (Official Build) (64-bit)` of Chrome browser.

**Comment by achyutgp** [comment]
@isaacplmann , I have only one `<context-menu>` component in my app. I am even passing the reference of context-menu in the `show` event, but no luck..

**Comment by isaacplmann** [comment]
@achyutgp
I'm out of ideas.

Please post a github repo that reproduces your issue. Or alternatively you could sign up for a [codementor](https://www.codementor.io/isaacplmann?utm_source=github&utm_medium=button&utm_term=isaacplmann&utm_campaign=github) session with me and I'll help debug your app.
